use_frameworks!

platform :ios, '10.0'

target 'JFUtils_Example' do
  pod 'JFUtils', :path => '../'

  target 'JFUtils_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
